apiVersion: v1
kind: Service
metadata:
  name: client-clusterip
spec:
  clusterIP: None  
  selector:
    component: web
  ports:
    - name: http2
      protocol: TCP
      port: 3000
      targetPort: 3000